[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[[ports]]
port = 8006
protocol = "TCP"

[volumes]
"/storage" = "windows_storage"
